// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvpEOjwFpAhB473ZGKP4jH-_yLpnVEJ9w',
    appId: '1:20288204688:web:5c48f7d1138dc6397d0d15',
    messagingSenderId: '20288204688',
    projectId: 'smarthome-13450',
    authDomain: 'smarthome-13450.firebaseapp.com',
    databaseURL: 'https://smarthome-13450-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-13450.appspot.com',
    measurementId: 'G-1EFG10REN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQwDSiUuOQqAzlZC1Dw6vbLfzmhVJUGM',
    appId: '1:20288204688:android:2fa48c13e1e0fcc17d0d15',
    messagingSenderId: '20288204688',
    projectId: 'smarthome-13450',
    databaseURL: 'https://smarthome-13450-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-13450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVoXDkI3D5zL4EwzK4hhQUcTDk-C6ngEI',
    appId: '1:20288204688:ios:b9295a18b67eb6857d0d15',
    messagingSenderId: '20288204688',
    projectId: 'smarthome-13450',
    databaseURL: 'https://smarthome-13450-default-rtdb.firebaseio.com',
    storageBucket: 'smarthome-13450.appspot.com',
    iosClientId: '20288204688-d37co3pnia0gufcnrj0pfmhfs5903skr.apps.googleusercontent.com',
    iosBundleId: 'com.gproject.smartHome',
  );
}
